/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package graphcalc;

/**
 *
 * @author admin
 */
public class GraphCalcGUI extends javax.swing.JFrame {

    /**
     * Creates new form GraphCalcGUI
     */
    public GraphCalcGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        graphCalcPanel1 = new graphcalc.GraphCalcPanel();
        calcField = new javax.swing.JTextField();
        calcPanel = new javax.swing.JPanel();
        button1 = new javax.swing.JButton();
        button2 = new javax.swing.JButton();
        button3 = new javax.swing.JButton();
        buttonPlus = new javax.swing.JButton();
        button4 = new javax.swing.JButton();
        button5 = new javax.swing.JButton();
        button6 = new javax.swing.JButton();
        buttonMinus = new javax.swing.JButton();
        button7 = new javax.swing.JButton();
        button8 = new javax.swing.JButton();
        button9 = new javax.swing.JButton();
        buttonTimes = new javax.swing.JButton();
        buttonReciprocal = new javax.swing.JButton();
        button0 = new javax.swing.JButton();
        buttonPoint = new javax.swing.JButton();
        buttonDividedBy = new javax.swing.JButton();
        buttonSin = new javax.swing.JButton();
        buttonCos = new javax.swing.JButton();
        buttonTan = new javax.swing.JButton();
        buttonX = new javax.swing.JButton();
        buttonSec = new javax.swing.JButton();
        buttonCsc = new javax.swing.JButton();
        buttonCot = new javax.swing.JButton();
        buttonLn = new javax.swing.JButton();
        buttonAsin = new javax.swing.JButton();
        buttonAcos = new javax.swing.JButton();
        buttonAtan = new javax.swing.JButton();
        buttonPower = new javax.swing.JButton();
        buttonAsec = new javax.swing.JButton();
        buttonAcsc = new javax.swing.JButton();
        buttonAcot = new javax.swing.JButton();
        buttonExp = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout graphCalcPanel1Layout = new javax.swing.GroupLayout(graphCalcPanel1);
        graphCalcPanel1.setLayout(graphCalcPanel1Layout);
        graphCalcPanel1Layout.setHorizontalGroup(
            graphCalcPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 450, Short.MAX_VALUE)
        );
        graphCalcPanel1Layout.setVerticalGroup(
            graphCalcPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        calcField.setEditable(false);
        calcField.setBackground(new java.awt.Color(255, 255, 255));
        calcField.setHorizontalAlignment(javax.swing.JTextField.RIGHT);
        calcField.setText("0");

        calcPanel.setLayout(new java.awt.GridLayout(8, 4));

        button1.setText("1");
        calcPanel.add(button1);

        button2.setText("2");
        calcPanel.add(button2);

        button3.setText("3");
        calcPanel.add(button3);

        buttonPlus.setText("+");
        calcPanel.add(buttonPlus);

        button4.setText("4");
        calcPanel.add(button4);

        button5.setText("5");
        calcPanel.add(button5);

        button6.setText("6");
        calcPanel.add(button6);

        buttonMinus.setText("-");
        calcPanel.add(buttonMinus);

        button7.setText("7");
        calcPanel.add(button7);

        button8.setText("8");
        calcPanel.add(button8);

        button9.setText("9");
        calcPanel.add(button9);

        buttonTimes.setText("*");
        calcPanel.add(buttonTimes);

        buttonReciprocal.setText("1/x");
        calcPanel.add(buttonReciprocal);

        button0.setText("0");
        calcPanel.add(button0);

        buttonPoint.setText(".");
        calcPanel.add(buttonPoint);

        buttonDividedBy.setText("/");
        calcPanel.add(buttonDividedBy);

        buttonSin.setText("sin");
        calcPanel.add(buttonSin);

        buttonCos.setText("cos");
        calcPanel.add(buttonCos);

        buttonTan.setText("tan");
        calcPanel.add(buttonTan);

        buttonX.setText("<html><i>x</i></html>");
        calcPanel.add(buttonX);

        buttonSec.setText("sec");
        calcPanel.add(buttonSec);

        buttonCsc.setText("csc");
        calcPanel.add(buttonCsc);

        buttonCot.setText("cot");
        calcPanel.add(buttonCot);

        buttonLn.setText("ln");
        calcPanel.add(buttonLn);

        buttonAsin.setText("Asin");
        calcPanel.add(buttonAsin);

        buttonAcos.setText("Acos");
        calcPanel.add(buttonAcos);

        buttonAtan.setText("Atan");
        calcPanel.add(buttonAtan);

        buttonPower.setText("<html><i>x</i><sup>y</sup></html>");
        calcPanel.add(buttonPower);

        buttonAsec.setText("Asec");
        calcPanel.add(buttonAsec);

        buttonAcsc.setText("Acsc");
        calcPanel.add(buttonAcsc);

        buttonAcot.setText("Acot");
        calcPanel.add(buttonAcot);

        buttonExp.setText("<html>e<sup>y</sup></html>");
        calcPanel.add(buttonExp);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(calcField)
                    .addComponent(calcPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(graphCalcPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(graphCalcPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(calcField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(calcPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 208, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(GraphCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(GraphCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(GraphCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(GraphCalcGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new GraphCalcGUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton button0;
    private javax.swing.JButton button1;
    private javax.swing.JButton button2;
    private javax.swing.JButton button3;
    private javax.swing.JButton button4;
    private javax.swing.JButton button5;
    private javax.swing.JButton button6;
    private javax.swing.JButton button7;
    private javax.swing.JButton button8;
    private javax.swing.JButton button9;
    private javax.swing.JButton buttonAcos;
    private javax.swing.JButton buttonAcot;
    private javax.swing.JButton buttonAcsc;
    private javax.swing.JButton buttonAsec;
    private javax.swing.JButton buttonAsin;
    private javax.swing.JButton buttonAtan;
    private javax.swing.JButton buttonCos;
    private javax.swing.JButton buttonCot;
    private javax.swing.JButton buttonCsc;
    private javax.swing.JButton buttonDividedBy;
    private javax.swing.JButton buttonExp;
    private javax.swing.JButton buttonLn;
    private javax.swing.JButton buttonMinus;
    private javax.swing.JButton buttonPlus;
    private javax.swing.JButton buttonPoint;
    private javax.swing.JButton buttonPower;
    private javax.swing.JButton buttonReciprocal;
    private javax.swing.JButton buttonSec;
    private javax.swing.JButton buttonSin;
    private javax.swing.JButton buttonTan;
    private javax.swing.JButton buttonTimes;
    private javax.swing.JButton buttonX;
    private javax.swing.JTextField calcField;
    private javax.swing.JPanel calcPanel;
    private graphcalc.GraphCalcPanel graphCalcPanel1;
    // End of variables declaration//GEN-END:variables
}
